import styles from '/src/styles/BookReader.module.scss'

function BookReader(){
    return (
        <>
        <div className={styles.container}>
            <h1>Название</h1>
            <div className={styles.text_container}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque, enim id mollis lacinia, lorem turpis condimentum lorem, vel auctor tortor odio quis dui. Vivamus maximus metus ac orci luctus ornare pulvinar ut nisi. Ut et odio elit. Nam nec erat ac dui tempor congue. Nam a convallis arcu, a consequat nunc. Integer lorem elit, porta non ex sed, suscipit fringilla nunc. Etiam molestie ac dui id lobortis. Sed blandit faucibus facilisis. Ut non ante sodales, mollis risus sed, gravida dui. Nunc cursus mi imperdiet augue laoreet, vel egestas nisi lacinia. Nulla eu ornare tortor, quis pretium ipsum. Duis viverra vehicula tempor. Nunc sed tempor purus. Sed non bibendum lacus. Vestibulum augue risus, ultricies ac laoreet in, iaculis sagittis massa.

Aliquam erat volutpat. Suspendisse et blandit tellus. Cras vel elit quis dui iaculis eleifend. Fusce luctus aliquet velit blandit finibus. Proin eu metus at ante tempor bibendum. Sed sit amet tempor purus. Nullam in ligula erat. Etiam sollicitudin diam a congue dictum.

Nam nec velit in risus ultrices sodales. Etiam consequat nibh vel ex rutrum bibendum a id quam. Suspendisse id metus in sem posuere porta vestibulum eget risus. Mauris eget malesuada est. Integer pulvinar bibendum velit eget congue. Donec molestie est at arcu imperdiet, consequat fermentum mauris vestibulum. Aliquam rutrum, ligula et faucibus posuere, eros urna fermentum libero, quis sodales magna quam nec magna. Donec id nulla id urna dignissim interdum. Morbi facilisis tellus lacus, ultricies accumsan est porta ut. Nam ultricies velit lectus, non placerat enim suscipit eu. Proin ultricies convallis neque, at tempus purus rhoncus sed.

Aenean posuere in risus et gravida. Praesent dapibus purus sit amet massa pulvinar tristique. Phasellus placerat ante nec arcu finibus, a bibendum sem bibendum. Praesent venenatis nibh quis tortor posuere mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras hendrerit, orci ut sagittis sollicitudin, libero quam tempor metus, et aliquam justo lectus nec risus. Pellentesque diam eros, aliquam eu ultricies vitae, ultricies quis odio. Donec placerat elit quis ligula sollicitudin hendrerit. Etiam sed varius justo. Integer vel massa rhoncus erat laoreet volutpat eleifend in augue. Nullam vestibulum augue non purus pretium blandit. Integer eu laoreet ex, eget vehicula nunc.

Suspendisse et enim lobortis, luctus sapien et, tristique nisi. Nullam accumsan quam eu nibh maximus, fringilla tempor nisi tincidunt. Sed posuere dignissim diam, sed pretium libero varius vitae. Sed a dictum neque, eget mattis mi. Praesent id erat velit. Vivamus vitae tempus enim, non blandit dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam nulla magna, varius nec pharetra vitae, ornare in metus. Curabitur sed metus vitae augue pretium laoreet. Duis nec leo massa. Aliquam id dui sagittis, elementum risus ut, vehicula lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque, enim id mollis lacinia, lorem turpis condimentum lorem, vel auctor tortor odio quis dui. Vivamus maximus metus ac orci luctus ornare pulvinar ut nisi. Ut et odio elit. Nam nec erat ac dui tempor congue. Nam a convallis arcu, a consequat nunc. Integer lorem elit, porta non ex sed, suscipit fringilla nunc. Etiam molestie ac dui id lobortis. Sed blandit faucibus facilisis. Ut non ante sodales, mollis risus sed, gravida dui. Nunc cursus mi imperdiet augue laoreet, vel egestas nisi lacinia. Nulla eu ornare tortor, quis pretium ipsum. Duis viverra vehicula tempor. Nunc sed tempor purus. Sed non bibendum lacus. Vestibulum augue risus, ultricies ac laoreet in, iaculis sagittis massa.

Aliquam erat volutpat. Suspendisse et blandit tellus. Cras vel elit quis dui iaculis eleifend. Fusce luctus aliquet velit blandit finibus. Proin eu metus at ante tempor bibendum. Sed sit amet tempor purus. Nullam in ligula erat. Etiam sollicitudin diam a congue dictum.

Nam nec velit in risus ultrices sodales. Etiam consequat nibh vel ex rutrum bibendum a id quam. Suspendisse id metus in sem posuere porta vestibulum eget risus. Mauris eget malesuada est. Integer pulvinar bibendum velit eget congue. Donec molestie est at arcu imperdiet, consequat fermentum mauris vestibulum. Aliquam rutrum, ligula et faucibus posuere, eros urna fermentum libero, quis sodales magna quam nec magna. Donec id nulla id urna dignissim interdum. Morbi facilisis tellus lacus, ultricies accumsan est porta ut. Nam ultricies velit lectus, non placerat enim suscipit eu. Proin ultricies convallis neque, at tempus purus rhoncus sed.

Aenean posuere in risus et gravida. Praesent dapibus purus sit amet massa pulvinar tristique. Phasellus placerat ante nec arcu finibus, a bibendum sem bibendum. Praesent venenatis nibh quis tortor posuere mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras hendrerit, orci ut sagittis sollicitudin, libero quam tempor metus, et aliquam justo lectus nec risus. Pellentesque diam eros, aliquam eu ultricies vitae, ultricies quis odio. Donec placerat elit quis ligula sollicitudin hendrerit. Etiam sed varius justo. Integer vel massa rhoncus erat laoreet volutpat eleifend in augue. Nullam vestibulum augue non purus pretium blandit. Integer eu laoreet ex, eget vehicula nunc.

Suspendisse et enim lobortis, luctus sapien et, tristique nisi. Nullam accumsan quam eu nibh maximus, fringilla tempor nisi tincidunt. Sed posuere dignissim diam, sed pretium libero varius vitae. Sed a dictum neque, eget mattis mi. Praesent id erat velit. Vivamus vitae tempus enim, non blandit dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam nulla magna, varius nec pharetra vitae, ornare in metus. Curabitur sed metus vitae augue pretium laoreet. Duis nec leo massa. Aliquam id dui sagittis, elementum risus ut, vehicula lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque, enim id mollis lacinia, lorem turpis condimentum lorem, vel auctor tortor odio quis dui. Vivamus maximus metus ac orci luctus ornare pulvinar ut nisi. Ut et odio elit. Nam nec erat ac dui tempor congue. Nam a convallis arcu, a consequat nunc. Integer lorem elit, porta non ex sed, suscipit fringilla nunc. Etiam molestie ac dui id lobortis. Sed blandit faucibus facilisis. Ut non ante sodales, mollis risus sed, gravida dui. Nunc cursus mi imperdiet augue laoreet, vel egestas nisi lacinia. Nulla eu ornare tortor, quis pretium ipsum. Duis viverra vehicula tempor. Nunc sed tempor purus. Sed non bibendum lacus. Vestibulum augue risus, ultricies ac laoreet in, iaculis sagittis massa.

Aliquam erat volutpat. Suspendisse et blandit tellus. Cras vel elit quis dui iaculis eleifend. Fusce luctus aliquet velit blandit finibus. Proin eu metus at ante tempor bibendum. Sed sit amet tempor purus. Nullam in ligula erat. Etiam sollicitudin diam a congue dictum.

Nam nec velit in risus ultrices sodales. Etiam consequat nibh vel ex rutrum bibendum a id quam. Suspendisse id metus in sem posuere porta vestibulum eget risus. Mauris eget malesuada est. Integer pulvinar bibendum velit eget congue. Donec molestie est at arcu imperdiet, consequat fermentum mauris vestibulum. Aliquam rutrum, ligula et faucibus posuere, eros urna fermentum libero, quis sodales magna quam nec magna. Donec id nulla id urna dignissim interdum. Morbi facilisis tellus lacus, ultricies accumsan est porta ut. Nam ultricies velit lectus, non placerat enim suscipit eu. Proin ultricies convallis neque, at tempus purus rhoncus sed.

Aenean posuere in risus et gravida. Praesent dapibus purus sit amet massa pulvinar tristique. Phasellus placerat ante nec arcu finibus, a bibendum sem bibendum. Praesent venenatis nibh quis tortor posuere mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras hendrerit, orci ut sagittis sollicitudin, libero quam tempor metus, et aliquam justo lectus nec risus. Pellentesque diam eros, aliquam eu ultricies vitae, ultricies quis odio. Donec placerat elit quis ligula sollicitudin hendrerit. Etiam sed varius justo. Integer vel massa rhoncus erat laoreet volutpat eleifend in augue. Nullam vestibulum augue non purus pretium blandit. Integer eu laoreet ex, eget vehicula nunc.

Suspendisse et enim lobortis, luctus sapien et, tristique nisi. Nullam accumsan quam eu nibh maximus, fringilla tempor nisi tincidunt. Sed posuere dignissim diam, sed pretium libero varius vitae. Sed a dictum neque, eget mattis mi. Praesent id erat velit. Vivamus vitae tempus enim, non blandit dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam nulla magna, varius nec pharetra vitae, ornare in metus. Curabitur sed metus vitae augue pretium laoreet. Duis nec leo massa. Aliquam id dui sagittis, elementum risus ut, vehicula lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque, enim id mollis lacinia, lorem turpis condimentum lorem, vel auctor tortor odio quis dui. Vivamus maximus metus ac orci luctus ornare pulvinar ut nisi. Ut et odio elit. Nam nec erat ac dui tempor congue. Nam a convallis arcu, a consequat nunc. Integer lorem elit, porta non ex sed, suscipit fringilla nunc. Etiam molestie ac dui id lobortis. Sed blandit faucibus facilisis. Ut non ante sodales, mollis risus sed, gravida dui. Nunc cursus mi imperdiet augue laoreet, vel egestas nisi lacinia. Nulla eu ornare tortor, quis pretium ipsum. Duis viverra vehicula tempor. Nunc sed tempor purus. Sed non bibendum lacus. Vestibulum augue risus, ultricies ac laoreet in, iaculis sagittis massa.

Aliquam erat volutpat. Suspendisse et blandit tellus. Cras vel elit quis dui iaculis eleifend. Fusce luctus aliquet velit blandit finibus. Proin eu metus at ante tempor bibendum. Sed sit amet tempor purus. Nullam in ligula erat. Etiam sollicitudin diam a congue dictum.

Nam nec velit in risus ultrices sodales. Etiam consequat nibh vel ex rutrum bibendum a id quam. Suspendisse id metus in sem posuere porta vestibulum eget risus. Mauris eget malesuada est. Integer pulvinar bibendum velit eget congue. Donec molestie est at arcu imperdiet, consequat fermentum mauris vestibulum. Aliquam rutrum, ligula et faucibus posuere, eros urna fermentum libero, quis sodales magna quam nec magna. Donec id nulla id urna dignissim interdum. Morbi facilisis tellus lacus, ultricies accumsan est porta ut. Nam ultricies velit lectus, non placerat enim suscipit eu. Proin ultricies convallis neque, at tempus purus rhoncus sed.

Aenean posuere in risus et gravida. Praesent dapibus purus sit amet massa pulvinar tristique. Phasellus placerat ante nec arcu finibus, a bibendum sem bibendum. Praesent venenatis nibh quis tortor posuere mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras hendrerit, orci ut sagittis sollicitudin, libero quam tempor metus, et aliquam justo lectus nec risus. Pellentesque diam eros, aliquam eu ultricies vitae, ultricies quis odio. Donec placerat elit quis ligula sollicitudin hendrerit. Etiam sed varius justo. Integer vel massa rhoncus erat laoreet volutpat eleifend in augue. Nullam vestibulum augue non purus pretium blandit. Integer eu laoreet ex, eget vehicula nunc.

Suspendisse et enim lobortis, luctus sapien et, tristique nisi. Nullam accumsan quam eu nibh maximus, fringilla tempor nisi tincidunt. Sed posuere dignissim diam, sed pretium libero varius vitae. Sed a dictum neque, eget mattis mi. Praesent id erat velit. Vivamus vitae tempus enim, non blandit dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam nulla magna, varius nec pharetra vitae, ornare in metus. Curabitur sed metus vitae augue pretium laoreet. Duis nec leo massa. Aliquam id dui sagittis, elementum risus ut, vehicula lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque, enim id mollis lacinia, lorem turpis condimentum lorem, vel auctor tortor odio quis dui. Vivamus maximus metus ac orci luctus ornare pulvinar ut nisi. Ut et odio elit. Nam nec erat ac dui tempor congue. Nam a convallis arcu, a consequat nunc. Integer lorem elit, porta non ex sed, suscipit fringilla nunc. Etiam molestie ac dui id lobortis. Sed blandit faucibus facilisis. Ut non ante sodales, mollis risus sed, gravida dui. Nunc cursus mi imperdiet augue laoreet, vel egestas nisi lacinia. Nulla eu ornare tortor, quis pretium ipsum. Duis viverra vehicula tempor. Nunc sed tempor purus. Sed non bibendum lacus. Vestibulum augue risus, ultricies ac laoreet in, iaculis sagittis massa.

Aliquam erat volutpat. Suspendisse et blandit tellus. Cras vel elit quis dui iaculis eleifend. Fusce luctus aliquet velit blandit finibus. Proin eu metus at ante tempor bibendum. Sed sit amet tempor purus. Nullam in ligula erat. Etiam sollicitudin diam a congue dictum.

Nam nec velit in risus ultrices sodales. Etiam consequat nibh vel ex rutrum bibendum a id quam. Suspendisse id metus in sem posuere porta vestibulum eget risus. Mauris eget malesuada est. Integer pulvinar bibendum velit eget congue. Donec molestie est at arcu imperdiet, consequat fermentum mauris vestibulum. Aliquam rutrum, ligula et faucibus posuere, eros urna fermentum libero, quis sodales magna quam nec magna. Donec id nulla id urna dignissim interdum. Morbi facilisis tellus lacus, ultricies accumsan est porta ut. Nam ultricies velit lectus, non placerat enim suscipit eu. Proin ultricies convallis neque, at tempus purus rhoncus sed.

Aenean posuere in risus et gravida. Praesent dapibus purus sit amet massa pulvinar tristique. Phasellus placerat ante nec arcu finibus, a bibendum sem bibendum. Praesent venenatis nibh quis tortor posuere mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras hendrerit, orci ut sagittis sollicitudin, libero quam tempor metus, et aliquam justo lectus nec risus. Pellentesque diam eros, aliquam eu ultricies vitae, ultricies quis odio. Donec placerat elit quis ligula sollicitudin hendrerit. Etiam sed varius justo. Integer vel massa rhoncus erat laoreet volutpat eleifend in augue. Nullam vestibulum augue non purus pretium blandit. Integer eu laoreet ex, eget vehicula nunc.

Suspendisse et enim lobortis, luctus sapien et, tristique nisi. Nullam accumsan quam eu nibh maximus, fringilla tempor nisi tincidunt. Sed posuere dignissim diam, sed pretium libero varius vitae. Sed a dictum neque, eget mattis mi. Praesent id erat velit. Vivamus vitae tempus enim, non blandit dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam nulla magna, varius nec pharetra vitae, ornare in metus. Curabitur sed metus vitae augue pretium laoreet. Duis nec leo massa. Aliquam id dui sagittis, elementum risus ut, vehicula lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque, enim id mollis lacinia, lorem turpis condimentum lorem, vel auctor tortor odio quis dui. Vivamus maximus metus ac orci luctus ornare pulvinar ut nisi. Ut et odio elit. Nam nec erat ac dui tempor congue. Nam a convallis arcu, a consequat nunc. Integer lorem elit, porta non ex sed, suscipit fringilla nunc. Etiam molestie ac dui id lobortis. Sed blandit faucibus facilisis. Ut non ante sodales, mollis risus sed, gravida dui. Nunc cursus mi imperdiet augue laoreet, vel egestas nisi lacinia. Nulla eu ornare tortor, quis pretium ipsum. Duis viverra vehicula tempor. Nunc sed tempor purus. Sed non bibendum lacus. Vestibulum augue risus, ultricies ac laoreet in, iaculis sagittis massa.

Aliquam erat volutpat. Suspendisse et blandit tellus. Cras vel elit quis dui iaculis eleifend. Fusce luctus aliquet velit blandit finibus. Proin eu metus at ante tempor bibendum. Sed sit amet tempor purus. Nullam in ligula erat. Etiam sollicitudin diam a congue dictum.

Nam nec velit in risus ultrices sodales. Etiam consequat nibh vel ex rutrum bibendum a id quam. Suspendisse id metus in sem posuere porta vestibulum eget risus. Mauris eget malesuada est. Integer pulvinar bibendum velit eget congue. Donec molestie est at arcu imperdiet, consequat fermentum mauris vestibulum. Aliquam rutrum, ligula et faucibus posuere, eros urna fermentum libero, quis sodales magna quam nec magna. Donec id nulla id urna dignissim interdum. Morbi facilisis tellus lacus, ultricies accumsan est porta ut. Nam ultricies velit lectus, non placerat enim suscipit eu. Proin ultricies convallis neque, at tempus purus rhoncus sed.

Aenean posuere in risus et gravida. Praesent dapibus purus sit amet massa pulvinar tristique. Phasellus placerat ante nec arcu finibus, a bibendum sem bibendum. Praesent venenatis nibh quis tortor posuere mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras hendrerit, orci ut sagittis sollicitudin, libero quam tempor metus, et aliquam justo lectus nec risus. Pellentesque diam eros, aliquam eu ultricies vitae, ultricies quis odio. Donec placerat elit quis ligula sollicitudin hendrerit. Etiam sed varius justo. Integer vel massa rhoncus erat laoreet volutpat eleifend in augue. Nullam vestibulum augue non purus pretium blandit. Integer eu laoreet ex, eget vehicula nunc.

Suspendisse et enim lobortis, luctus sapien et, tristique nisi. Nullam accumsan quam eu nibh maximus, fringilla tempor nisi tincidunt. Sed posuere dignissim diam, sed pretium libero varius vitae. Sed a dictum neque, eget mattis mi. Praesent id erat velit. Vivamus vitae tempus enim, non blandit dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam nulla magna, varius nec pharetra vitae, ornare in metus. Curabitur sed metus vitae augue pretium laoreet. Duis nec leo massa. Aliquam id dui sagittis, elementum risus ut, vehicula lorem.</p>
            </div>
        </div>
        </>
    )
}

export default BookReader